# Generated by Django 5.0.6 on 2024-07-11 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'MarcaMoto',
            },
        ),
        migrations.CreateModel(
            name='MarcaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'MarcaRepuesto',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricacion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nro', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'UnidadMedida',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca_moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marcamoto')),
            ],
            options={
                'db_table': 'Modelo',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('numero_parte', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('marca_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marcarepuesto')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pais')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor')),
            ],
            options={
                'db_table': 'Repuesto',
            },
        ),
        migrations.CreateModel(
            name='RepuestoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Repuesto Simple',
                'verbose_name_plural': 'Repuestos Simples',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.repuesto',),
        ),
        migrations.CreateModel(
            name='RepuestoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.modelo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.repuesto')),
            ],
            options={
                'db_table': 'RepuestoModelo',
                'unique_together': {('repuesto', 'modelo')},
            },
        ),
        migrations.AddField(
            model_name='repuesto',
            name='modelos',
            field=models.ManyToManyField(through='inventario.RepuestoModelo', to='inventario.modelo'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadmedida'),
        ),
    ]
